USE elearning_system;

UPDATE lessons
SET content = CASE
    WHEN lesson_id BETWEEN 1 AND 6 THEN CONCAT(
        'Bài học "', lesson_title, '" nằm trong lộ trình Lập trình Web căn bản và được viết lại thành một phần đọc dài để học viên có thể mở ra, đọc kỹ và ghi chú ngay trên giao diện web. Nội dung trong bài không chỉ giải thích khái niệm mà còn mô tả bối cảnh sử dụng, các bước thao tác thủ công, các lỗi thường gặp và cách tự kiểm tra kết quả sau mỗi lần thực hành. ',
        'Học viên cần bắt đầu bằng việc xác định mục tiêu của bài, ghi rõ mình cần tạo ra được sản phẩm gì sau khi học xong, ví dụ như một file HTML chuẩn, một layout CSS dễ đọc, hoặc một đoạn JavaScript có khả năng tương tác với người dùng. ',
        'Trong quá trình học, nên chia bài thành ba pha rõ ràng: đọc hiểu lý thuyết, làm lại từng thao tác theo hướng dẫn, sau đó tự biến đổi thành một ví dụ mang dấu ấn cá nhân. Nếu bài đang nhắc đến công cụ, học viên cần note lại tên công cụ, lý do phải dùng nó, và cách nó hỗ trợ tăng tốc độ làm việc trong dự án thực tế. ',
        'Ngoài phần kỹ thuật, bài đọc này nhấn mạnh tư duy tổ chức dự án: cách đặt tên file, sắp xếp thư mục, tách riêng phần hình ảnh, style và script, đồng thời giữ cho mã nguồn sạch để đọc về sau. Đây là thói quen nhỏ nhưng có giá trị rất lớn khi học viên bắt đầu làm nhóm hoặc cần sửa code sau nhiều tuần. ',
        'Một điểm quan trọng khác là khả năng tự kiểm tra. Sau mỗi đoạn kiến thức, học viên nên mở trình duyệt, quan sát kết quả hiển thị, so sánh với mục tiêu ban đầu và ghi lại bất kỳ khác biệt nào. Khi giao diện chưa đúng, không nên sửa ngẫu nhiên mà cần kiểm tra từ cấu trúc HTML, đến class CSS, rồi mới đến script tương tác. ',
        'Phần đọc mở rộng của bài hướng học viên đến cách tự đặt câu hỏi: tại sao thẻ này cần thiết, tại sao thuộc tính kia ảnh hưởng đến bố cục, tại sao một dòng script có thể làm thay đổi nội dung trên màn hình. Khi giữ được cách học có hệ thống như vậy, học viên sẽ không chỉ nhớ được thao tác mà còn có thể tự tin viết lại từ đầu trong một dự án mới.'
    )
    WHEN lesson_id BETWEEN 7 AND 12 THEN CONCAT(
        'Bài học "', lesson_title, '" thuộc chủ đề ReactJS và được mở rộng thành phần bài đọc chi tiết để học viên không chỉ xem video mà còn có tài liệu nền để ôn lại tư duy component. Phần đọc giải thích rõ cách React chia giao diện thành nhiều khối nhỏ, mỗi khối có trách nhiệm riêng, và vì sao cách tiếp cận này giúp dự án dễ bảo trì hơn so với việc viết một file lớn chứa tất cả logic. ',
        'Mỗi bài trong cụm này đều cần học viên phân biệt được ba lớp suy nghĩ: giao diện hiển thị gì, dữ liệu nằm ở đâu, và sự kiện nào sẽ làm dữ liệu thay đổi. Khi nắm được ba lớp này, học viên sẽ hiểu vì sao JSX được viết giống HTML nhưng lại mang sức mạnh của JavaScript, vì sao props dùng để truyền dữ liệu xuống dưới, và vì sao state là nơi lưu trạng thái thay đổi theo tương tác. ',
        'Phần đọc cũng đưa ra một cách học rất thực chiến: mỗi khi gặp một khái niệm như lifecycle, form handling hay useEffect, học viên nên tự tạo ví dụ nhỏ chỉ gồm một mục tiêu duy nhất. Ví dụ, nếu đang học useEffect, hãy tạo một component chỉ để fetch danh sách và hiển thị loading; nếu đang học event handling, hãy tạo một form nhỏ để kiểm tra giá trị nhập vào theo từng bước. ',
        'Nội dung mở rộng của bài nhấn mạnh những lỗi thường gặp ở người mới học React như cập nhật state sai cách, đặt quá nhiều logic vào một component, quên dependencies trong useEffect hoặc đặt tên biến không rõ nghĩa. Mỗi lỗi đều được tiếp cận theo hướng phòng ngừa: tách component nhỏ, đặt tên theo ý nghĩa nghiệp vụ, và mở console để kiểm tra sự thay đổi của dữ liệu thay vì sửa theo cảm tính. ',
        'Bên cạnh phần kỹ thuật, bài đọc còn hướng học viên đến cách tư duy dự án: một tính năng tốt không chỉ đúng mà còn dễ test, dễ mở rộng và dễ cho người khác đọc lại. Vì vậy, sau khi học xong từng bài, học viên nên tự viết một ghi chú ngắn gồm input, output, state và event liên quan, coi đó như mini design note cho chính mình. ',
        'Nếu học viên đọc kỹ và thực hành theo trình tự này, các bài React sẽ không còn là việc học thuộc các hook một cách rời rạc, mà trở thành một hành trình hiểu được cách xây dựng giao diện động, cách đồng bộ dữ liệu, và cách phát triển một ứng dụng web có cấu trúc rõ ràng.'
    )
    WHEN lesson_id BETWEEN 13 AND 18 THEN CONCAT(
        'Bài học "', lesson_title, '" nằm trong cụm Facebook Ads và được viết lại thành một bài đọc đầy đủ để học viên có thể vừa học kiến thức marketing, vừa xây dựng bộ ghi chú nghiệp vụ cho riêng mình. Khác với phần kỹ thuật thuần túy, chủ đề này cần học viên hiểu tư duy trước khi chạm vào trình quản lý quảng cáo, bởi vì chỉ cần sai ở bước chân dung đối tượng hoặc thông điệp, ngân sách sẽ bị tiêu hao mà không tạo ra kết quả. ',
        'Phần đọc phân tích từng lớp của một chiến dịch hiệu quả: chân dung khách hàng, vấn đề khách gặp phải, thông điệp giải quyết, mẫu nội dung thu hút, và cuối cùng mới là thiết lập chiến dịch. Học viên cần hiểu rằng một hook tốt chỉ là điểm mở đầu; điều giữ người xem ở lại và hành động là mức độ liên quan giữa nội dung với nhu cầu thật của họ. ',
        'Tài liệu mở rộng trong bài cũng hướng dẫn cách đọc chỉ số theo logic kinh doanh thay vì đọc từng con số riêng lẻ. Ví dụ, CPM cao có thể là dấu hiệu nội dung hoặc đối tượng chưa ổn; CPC thấp nhưng không có chuyển đổi thì vấn đề nằm ở landing page hoặc lời hứa thông điệp; tần suất quá cao có thể báo hiệu nội dung đang bị lặp lại đến mức gây mệt mỏi. ',
        'Để học hiệu quả, học viên nên tái hiện từng tình huống bằng cách tự đặt câu hỏi sau mỗi bước: bài này đang bán cho ai, người đó đang sợ điều gì, thông điệp nào khiến họ dừng lại, và hành động nào được kỳ vọng sau khi bấm vào quảng cáo. Khi trả lời được bộ câu hỏi này, việc viết content, chọn target và tối ưu ngân sách sẽ dễ dàng hơn rất nhiều. ',
        'Phần đọc dài này cũng khuyên học viên giữ một bảng nhật ký chiến dịch gồm ngày chạy, góc content, đối tượng, ngân sách, kết quả và bài học rút ra. Chỉ cần duy trì thói quen này trong vài tuần, học viên sẽ thấy mình không còn tối ưu theo cảm giác mà theo dữ liệu và bối cảnh sử dụng thật. ',
        'Kết thúc bài, mục tiêu không phải chỉ là biết bấm nút tạo quảng cáo, mà là có khả năng phân tích, giải thích và đề xuất điều chỉnh một cách có cơ sở. Đây là nền tảng để học viên đi xa hơn ở các bài remarketing, scale ngân sách và xây dựng hệ thống chuyển đổi bền vững.'
    )
    WHEN lesson_id BETWEEN 19 AND 24 THEN CONCAT(
        'Bài học "', lesson_title, '" thuộc chủ đề TikTok Content, livestream và xây dựng thương hiệu cá nhân. Phần content được mở rộng thành bài đọc dài để học viên có thể đọc liền mạch trên web, hiểu được vì sao một video ngắn vẫn cần cấu trúc chặt chẽ, vì sao livestream không chỉ là nói liên tục, và vì sao thương hiệu cá nhân là tài sản giúp gia tăng chuyển đổi lâu dài. ',
        'Nội dung bài phân tích rõ ba tầng của một nội dung hiệu quả: giữ chân ở ba giây đầu, dẫn dắt ở phần giữa, và kết thúc bằng hành động rõ ràng. Học viên cần hiểu rằng người xem trên nền tảng video ngắn ra quyết định ở tốc độ rất nhanh, nên từng câu mở đầu, từng khung hình và từng dòng chữ hiện trên video đều phải có lý do tồn tại. ',
        'Với các bài liên quan đến quay dựng, phần đọc nhấn mạnh quá trình chuẩn bị thay vì chỉ nhìn vào lúc bấm quay. Bối cảnh, ánh sáng, âm thanh, trang phục, script ngắn, đạo cụ minh họa và vị trí camera đều ảnh hưởng trực tiếp đến cảm nhận chuyên nghiệp của video. Khi học viên biết lập checklist trước lúc quay, chất lượng video sẽ ổn định hơn và tiết kiệm rất nhiều thời gian edit. ',
        'Với livestream, bài đọc mở rộng cách chia vai trò trong một buổi live: người dẫn dắt, người đọc comment, người xử lý đơn và người theo dõi chỉ số. Dù học viên tự live một mình hay đi theo nhóm, cách chia tác vụ trên giấy trước khi lên sóng sẽ giúp buổi live bớt rối, bớt quên thông tin và giữ được nhịp bán hàng. ',
        'Bên cạnh kỹ thuật, bài đọc cũng nhắc học viên giữ góc nhìn thương hiệu: nội dung nào phù hợp với hình ảnh mình muốn xây, đối tượng nào mình muốn phục vụ, và giá trị nào cần lặp lại để khán giả nhớ đến. Không phải video nào cũng cần viral; điều quan trọng hơn là video đúng người, đúng thông điệp và dẫn về đúng mục tiêu kinh doanh. ',
        'Nếu học viên ôn kỹ phần đọc này, mỗi bài trong cụm TikTok sẽ trở thành một bước trong hệ thống sản xuất nội dung hoàn chỉnh: từ lên ý tưởng, viết script, quay, dựng, livestream, phân tích phản hồi, đến xây dựng hình ảnh cá nhân và mở rộng hợp tác với nhãn hàng.'
    )
    WHEN lesson_id BETWEEN 25 AND 30 THEN CONCAT(
        'Bài học "', lesson_title, '" thuộc nhóm Tiếng Anh công việc và được mở rộng thành một bài đọc dài để học viên có thể vừa luyện ngôn ngữ, vừa hiểu bối cảnh giao tiếp chuyên nghiệp. Nội dung bài không đặt mục tiêu học thuộc từng câu mẫu một cách máy móc, mà hướng tới việc sử dụng ngôn ngữ đúng tình huống, đúng thái độ và đúng mục tiêu giao tiếp. ',
        'Trong các bài về phát âm, giao tiếp và phỏng vấn, học viên cần quan tâm đến ba mức độ: từ vựng cần biết, cấu trúc cần dùng, và cách phát âm để người nghe hiểu đúng ý. Rất nhiều học viên biết từ nhưng lại ngại nói, vì vậy phần đọc này khuyên học viên đọc thành tiếng, ghi âm lại giọng nói của mình, sau đó đối chiếu với mẫu để chỉnh dần từng điểm nhỏ. ',
        'Với bài về email, họp, đàm phán hay thuyết trình, phần content được viết theo tư duy nghiệp vụ: trước khi viết hoặc nói, cần biết đối tượng là ai, mục tiêu của thông điệp là gì, và mức độ trang trọng cần đạt đến đâu. Khi hiểu bối cảnh, học viên sẽ biết vì sao một câu lịch sự nhưng ngắn gọn lại hiệu quả hơn một đoạn dài dòng và mơ hồ. ',
        'Nội dung bài cũng chèn thêm những khung mẫu mà học viên có thể biến đổi: cách mở đầu email, cách đặt câu hỏi làm rõ thông tin, cách trình bày quan điểm trong cuộc họp, cách xin thêm thời gian để suy nghĩ trong phỏng vấn, và cách chốt thông điệp trong một bài thuyết trình dự án. Những khung mẫu này giúp học viên có điểm tựa để luyện tập lặp đi lặp lại cho đến khi trở nên tự nhiên. ',
        'Phần đọc nhấn mạnh một nguyên tắc quan trọng: học ngôn ngữ để sử dụng, không phải để học thuộc. Sau mỗi bài, học viên nên viết lại một đoạn ngắn bằng tình huống của chính mình, đổi tên công ty, đổi tên dự án, đổi mục tiêu trao đổi, và tự tập nói thành tiếng theo bối cảnh thật. Cách học này giúp trí nhớ sâu hơn và dễ ứng dụng hơn rất nhiều. ',
        'Khi học xong cụm bài này, học viên lý tưởng nhất là đạt được sự tự tin nền tảng: có thể tự giới thiệu, trao đổi, viết email, trả lời phỏng vấn và trình bày ý tưởng một cách rõ ràng. Đó chính là giá trị lớn nhất của bài đọc mở rộng này.'
    )
    WHEN lesson_id BETWEEN 31 AND 36 THEN CONCAT(
        'Bài học "', lesson_title, '" nằm trong chủ đề Excel và Power BI, được bổ sung phần đọc dài để học viên hiểu cả thao tác kỹ thuật lẫn tư duy xử lý dữ liệu. Nhiều người học công cụ theo kiểu thuộc từng hàm, từng nút bấm, nhưng khi gặp file dữ liệu thật thì lại lúng túng vì không biết bắt đầu từ đâu. Bài đọc này được viết để sửa đúng điểm đó. ',
        'Nội dung của bài dẫn học viên đi theo quy trình rõ ràng: xác định bài toán, kiểm tra chất lượng dữ liệu, làm sạch dữ liệu, chọn công cụ phù hợp, sau đó mới đến trình bày kết quả. Nếu dữ liệu ban đầu bị trùng, bị thiếu, sai định dạng ngày tháng hoặc sai logic, thì biểu đồ đẹp đến đâu cũng không tạo ra quyết định đúng. ',
        'Với Excel, phần đọc mở rộng cách tư duy theo công thức: xác định đầu vào, điều kiện, kết quả mong muốn, sau đó mới chọn hàm IF, AND, OR, VLOOKUP hay XLOOKUP. Học viên không nên học hàm theo tên gọi, mà cần học theo bài toán: cần tìm gì, cần so sánh gì, cần trả về kết quả nào và nếu dữ liệu sai thì sẽ xử lý ra sao. ',
        'Với Power BI, bài đọc nhấn mạnh việc xây dựng mô hình dữ liệu là nền tảng của mọi dashboard hữu ích. Một dashboard không chỉ để đẹp, mà để giúp người xem ra quyết định nhanh. Vì vậy, học viên cần ghi nhớ sự khác nhau giữa metric, dimension, filter, drill-down, và ý nghĩa của mỗi visualization trong từng tình huống kinh doanh cụ thể. ',
        'Phần nội dung dài này cũng khuyên học viên tạo bộ checklist riêng trước khi nộp báo cáo: tên cột đã rõ chưa, đơn vị đã thống nhất chưa, màu sắc có nhất quán không, biểu đồ có giải đáp được câu hỏi kinh doanh không, và nếu sếp chỉ xem ba mươi giây thì họ có hiểu ngay thông điệp chính hay không. ',
        'Sau khi đọc và áp dụng đều đặn, học viên sẽ tiếp cận dữ liệu một cách có hệ thống hơn: không còn chỉ là biết bấm công cụ, mà là biết đặt câu hỏi đúng, chuẩn hóa dữ liệu đúng, và trình bày insight đúng mục tiêu.'
    )
    WHEN lesson_id BETWEEN 37 AND 42 THEN CONCAT(
        'Bài học "', lesson_title, '" thuộc nhóm Canva và thiết kế nội dung bán hàng. Phần content được mở rộng thành bài đọc dài để học viên hiểu rằng thiết kế không chỉ là kéo thả cho đẹp, mà là quá trình sắp xếp thông tin sao cho người xem nhìn vào là hiểu ngay thông điệp và có lý do để hành động. ',
        'Trong bài, học viên được nhắc lại nền tảng của bố cục: điểm nhìn chính, thứ bậc thông tin, khoảng trắng, sự lặp lại có chủ ý, và cách giữ cho mỗi khung hình có một thông điệp trung tâm. Cho dù đang thiết kế bài đăng social, banner website, video ngắn hay CV, nếu bố cục rối, thông điệp sẽ bị yếu đi rất nhanh. ',
        'Phần đọc mở rộng cũng phân tích màu sắc và typography dưới góc nhìn ứng dụng. Màu không chỉ để đẹp mà còn để dẫn mắt người xem, nhấn mạnh ưu đãi, tách khu vực quan trọng và tạo cảm xúc phù hợp với thương hiệu. Font chữ không chỉ để đọc mà còn để xác lập phong cách, độ trang trọng và mục tiêu của tài liệu. ',
        'Với các bài về ads image, banner và video ngắn, bài đọc đưa học viên về lại câu hỏi căn bản: ai sẽ nhìn thấy sản phẩm này, họ có bao lâu để quyết định dừng lại, và thông điệp nào cần được đặt ở vị trí nổi bật nhất. Chỉ khi trả lời được những câu hỏi này, học viên mới biết nên đặt tiêu đề ở đâu, màu nào cần nhấn, hình nào cần để lớn và CTA nào cần rõ ràng. ',
        'Nội dung bài còn khuyên học viên tạo bộ màu và bộ layout riêng cho từng mục đích, ví dụ một set cho khuyến mãi, một set cho giáo dục, một set cho profile cá nhân. Khi làm được như vậy, tốc độ sản xuất nội dung sẽ nhanh hơn, tổng thể hình ảnh sẽ đồng bộ hơn và học viên sẽ dễ phát hiện điểm cần cải tiến qua từng lần đăng bài. ',
        'Kết quả mong muốn sau cụm bài này là học viên không chỉ biết sử dụng Canva, mà còn hiểu cách xây dựng một ngôn ngữ hình ảnh nhất quán cho thương hiệu, giúp mỗi bài đăng, mỗi banner và mỗi tài liệu đều truyền đạt thông điệp mạnh mẽ và chuyên nghiệp hơn.'
    )
    WHEN lesson_id BETWEEN 43 AND 48 THEN CONCAT(
        'Bài học "', lesson_title, '" nằm trong chủ đề kỹ năng thuyết trình và được mở rộng thành một bài đọc dài để học viên có tài liệu nền cho việc luyện tập. Thuyết trình không phải chỉ là nói trước đám đông; đó là khả năng tổ chức ý tưởng, quan sát người nghe, điều tiết năng lượng và đưa thông điệp đến đúng mục tiêu trong một khoảng thời gian giới hạn. ',
        'Phần đọc giải thích rõ cách xây bộ khung bài nói: mở đầu để tạo chú ý, thân bài để sắp xếp luận điểm, và kết thúc để đóng lại thông điệp hoặc kêu gọi hành động. Nếu bài nói không có cấu trúc, người nghe sẽ nhanh chóng mất mạch. Nếu cấu trúc tốt, ngay cả nội dung phức tạp cũng trở nên dễ theo dõi hơn nhiều. ',
        'Với các bài về mở đầu, ngôn ngữ hình thể, giọng nói và storytelling, tài liệu nhấn mạnh việc tập theo từng lớp kỹ năng nhỏ. Một người học không nên cố gắng sửa tất cả trong một lần. Hôm nay có thể chỉ tập tốc độ nói và điểm dừng; buổi sau tập ánh mắt và tư thế; buổi tiếp theo mới ghép thêm phần kể chuyện và xử lý câu hỏi. ',
        'Nội dung bài cũng khuyên học viên ghi hình lại chính mình trong lúc luyện tập. Việc xem lại video rất hiệu quả vì nó cho thấy những điểm mà lúc đang nói mình không nhận ra, như từ lặp lại quá nhiều, cử động tay bị thừa, mắt nhìn lên trần, hay giọng nói bị đều và thiếu nhấn. Đây là cách cải thiện nhanh và thực tế nhất. ',
        'Trong bối cảnh online, bài đọc mở rộng thêm về khung hình, ánh sáng, góc máy và khoảng cách đến camera. Người thuyết trình online không có sân khấu vật lý, nên khung hình chính là sân khấu mới. Một setup gọn gàng, rõ mặt, âm thanh sạch và điểm nhìn ổn định sẽ tăng mức độ tin tưởng của người nghe rất nhiều. ',
        'Khi ôn kỹ cụm bài này, học viên sẽ nâng dần khả năng biến ý tưởng thành một bài nói có trình tự, có cảm xúc và có sức thuyết phục. Đó là nền tảng cần thiết cho phỏng vấn, báo cáo, pitching và bất kỳ tình huống giao tiếp chuyên nghiệp nào sau này.'
    )
    WHEN lesson_id BETWEEN 49 AND 54 THEN CONCAT(
        'Bài học "', lesson_title, '" thuộc nhóm tài chính cá nhân và đầu tư cơ bản. Phần content được mở rộng thành bài đọc dài để học viên có thể đọc chậm, hiểu nguyên lý và xây dựng được một hệ thống quản lý tiền bạc phù hợp với chính mình. Mục tiêu của chủ đề này không phải tạo cảm giác làm giàu nhanh, mà là giúp học viên biết rõ dòng tiền của mình đang đi đâu, vì sao cần quỹ dự phòng, và cách đưa ra quyết định tài chính có kỷ luật. ',
        'Nội dung bài bắt đầu từ những nền tảng nhỏ nhất: ghi chép, phân loại chi tiêu, đặt ngưỡng cảnh báo và xác định khoản nào là nhu cầu thật. Người học thường muốn nhảy thẳng sang đầu tư, nhưng nếu chưa biết dòng tiền hàng tháng của mình đang vận hành thế nào thì rất dễ đầu tư trong tâm lý thiếu ổn định và dễ bỏ cuộc giữa chừng. ',
        'Với các bài về nợ, thẻ tín dụng, quỹ dự phòng và bảo hiểm, phần đọc giải thích logic ưu tiên: giảm rủi ro trước, mở rộng cơ hội sau. Học viên cần nhìn nợ dưới góc nhìn dòng tiền, cần biết khoản nào có lãi suất cao, khoản nào cần đóng ngay, khoản nào cần đàm phán lại, và tại sao một bộ đệm tài chính nhỏ lại có thể giúp mình bình tĩnh hơn trong nhiều quyết định lớn. ',
        'Với các bài về đầu tư, thị trường chứng khoán và quỹ chỉ số, bài đọc nhấn mạnh tính kỷ luật lâu dài hơn là dự đoán ngắn hạn. Học viên nên ghi nhớ sự khác nhau giữa tiết kiệm, đầu tư và đầu cơ; biết mục tiêu của mình là bảo toàn, tăng trưởng hay tạo dòng tiền; và xác định được thời gian đầu tư trước khi lựa chọn sản phẩm. ',
        'Nội dung mở rộng cũng đưa ra một khung tự đánh giá quyết định tài chính: mình đã hiểu sản phẩm này chưa, nếu giá giảm mạnh mình có bình tĩnh được không, nếu mất việc ba tháng thì quyết định này có gây áp lực lên dòng tiền không, và liệu mình đang đầu tư vì kế hoạch hay vì sợ bỏ lỡ cơ hội. ',
        'Nếu học viên coi mỗi bài trong cụm này là một bước xây nền hệ thống tài chính cá nhân, thì sau một thời gian sẽ có được khả năng quản lý tiền rõ ràng hơn, biết ưu tiên mục tiêu tốt hơn, và biết cách ra quyết định tài chính bình tĩnh, có kỷ luật và bền vững.'
    )
    WHEN lesson_id BETWEEN 55 AND 60 THEN CONCAT(
        'Bài học "', lesson_title, '" thuộc chủ đề vận hành shop online và thương mại điện tử. Phần content được mở rộng thành bài đọc dài để học viên hiểu rằng kinh doanh trên sàn không chỉ là đăng sản phẩm và chờ đơn, mà là một chuỗi vận hành liên tục từ khâu nghiên cứu, trình bày, chốt đơn, đóng gói, chăm sóc và giữ chân khách hàng quay lại. ',
        'Trong bài, học viên được hướng dẫn nhìn shop như một hệ thống. Tiêu đề, hình ảnh, mô tả và giá bán là lớp giao tiếp đầu tiên; chất lượng phản hồi, tốc độ xử lý đơn và trải nghiệm sau mua là lớp tạo uy tín; còn khuyến mãi, voucher và chương trình quay lại là lớp duy trì doanh thu về sau. Khi một trong các lớp này yếu, tổng hiệu quả của shop sẽ giảm dù bạn có chạy quảng cáo tốt đến đâu. ',
        'Phần đọc mở rộng từng bài theo hướng ứng dụng. Nếu bài đang nói về tối ưu tiêu đề, học viên cần biết cách chèn từ khóa vào đúng vị trí, cách đặt lợi ích ở phần đầu, và cách tránh tiêu đề quá chung chung. Nếu bài đang nói về đối thủ, học viên cần biết quan sát phần hình ảnh, giá, đánh giá, feedback và ưu đãi thay vì chỉ nhìn vào giá bán. ',
        'Với vận hành đơn hàng và chăm sóc khách, tài liệu nhấn mạnh một nguyên tắc rất thực tế: shop tăng trưởng bền vững là shop giảm lỗi lặp lại. Vì vậy, học viên nên tạo checklist đóng gói, kịch bản trả lời nhanh, quy trình xử lý khi khách hủy đơn hoặc phàn nàn, và cách ghi nhận lý do khách không mua để tối ưu lại ở các bước trước đó. ',
        'Nội dung bài cũng đề cập đến việc xây dựng tệp khách hàng trung thành. Trong thương mại điện tử, một đơn hàng thành công là tốt, nhưng một khách quay lại nhiều lần mới là tài sản. Do đó, shop cần có cách nhớ tên sản phẩm bán chạy, ghi nhận nhóm khách mua lặp lại, và tạo các cơ chế như voucher, combo, ưu đãi sau mua hoặc tin nhắn nhắc lại đúng thời điểm. ',
        'Kết thúc cụm bài này, học viên cần đạt được cách nhìn toàn diện hơn về một shop online: không chỉ tập trung vào doanh thu trước mắt, mà biết cách tối ưu toàn bộ hành trình khách hàng để tạo trải nghiệm tốt, giảm chi phí lỗi và tăng giá trị vòng đời của mỗi người mua.'
    )
    ELSE CONCAT(
        'Nội dung mở rộng cho bài học "', COALESCE(lesson_title, 'không xác định'), '" được bổ sung để đảm bảo trên giao diện web, học viên lúc nào cũng có một bài đọc đủ dài để ôn tập. Phần đọc này giải thích mục tiêu của bài, bối cảnh áp dụng, cách tự học và cách tự đánh giá kết quả sau khi xem video hoặc tham gia buổi học. ',
        'Học viên nên đọc bài theo nhóm câu hỏi cố định: bài này dạy mình điều gì, sau bài này mình tạo ra được sản phẩm hay kỹ năng nào, đâu là những bước thực hành quan trọng nhất, và nếu tự làm lại một mình thì cần chuẩn bị những gì. Cách đọc có chủ đích sẽ giúp khả năng ghi nhớ tốt hơn nhiều so với việc lướt qua thông tin. ',
        'Phần mở rộng cũng nhắc đến việc ghi chú, tổng hợp và thực hành lại bằng ví dụ riêng. Mỗi bài học chỉ thật sự có giá trị khi học viên biến nó thành một thao tác, một sản phẩm nhỏ hoặc một thói quen có thể lặp lại trong dự án hay công việc thực tế. ',
        'Nếu bài này là bài test, bài bổ sung hoặc bài đang được tạo mới, đoạn content này vẫn được viết theo hướng chung nhất quán để giao diện học tập không bị trống và học viên vẫn có một khung đọc hiểu, tự ôn và ghi chú trong quá trình học.'
    )
END;
